######################################################################
# Automatically generated by qmake (3.0) Tue Mar 22 12:00:31 2016
######################################################################

TEMPLATE = app
TARGET = CSCE452-Project3
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h robot.h \
    udp.h
SOURCES += main.cpp mainwindow.cpp robot.cpp \
    udp.cpp
RESOURCES += robot.qrc
QT += widgets gui
QT += core
QT += network
